### ISSUE TITLE
Doesn't work on A11

### ISSUE THREAD

**Issue by chaoscreater** [zeronao/device_xiaomi_cannon-OFRP#4]
I'm on A11 MIUI 12.5.7. I can boot into A12 OrangeFox, but it just sits there at the main boot screen with the orangeFox logo and orange background. I can't get past that screen. Tried flashing via recovery and bootloader, both have the same result.

A11 OrangeFox works fine, but not A12 OrangeFox.

**Comment by zeronao** [comment]
I've sold the phone,so i don't maintain it anymore
